### ISSUE TITLE
[feature] What is the size of the scroll buffer? Add an option to increased it.

### ISSUE THREAD

**Issue by ddofborg** [pvolok/mprocs#107]
What is the size (in lines or bytes) of the scroll buffer?

**Comment by jayvdb** [comment]
It is 1000 defined at https://github.com/pvolok/mprocs/blob/08d17adebd110501106f86124ef1955fb2beb881/src/proc/mod.rs#L58C14-L58C27

**Comment by pvolok** [comment]
Reopening. Still need to add code for reading value from parsed yaml.

**Comment by jayvdb** [comment]
I believe this has been solved now.
