### ISSUE TITLE
Ability to use arrow keys

### ISSUE THREAD

**Issue by adriaand007** [pvolok/mprocs#11]
Immediately I thought this is a nice to have
Problem is that mc (Midnight Commander) arrow keys is not working
Running on Fedora 36
Here with my json config
![image](https://user-images.githubusercontent.com/13329360/169956814-f013d536-c1ae-44a7-a850-841a1a02bec0.png)

**Comment by pvolok** [comment]
It's also the case for Midnight Commander on Macos. I will need to read more about encoding key codes to fix this.

**Comment by pvolok** [comment]
Fixed in master. I will release a new version tomorrow.

**Comment by o-az** [comment]
> Fixed in master. I will release a new version tomorrow.

Any updates on this? May I also propose including a configurable config file? Maybe `.mprocsrc`. User can customize settings, theme, layout, etc. I think it would be a great feature. I would be happy to help.

**Comment by pvolok** [comment]
Released 0.2.3 which includes the fix.

> May I also propose including a configurable config file? Maybe .mprocsrc. User can customize settings, theme, layout, etc. I think it would be a great feature. I would be happy to help.

@o-az Yes, I'm planning to add a config file. But currently there are no global settings, so there is nothing to configure. But I want to add an ability to configure the key bindings which would be configurable either via global or local config.
