### ISSUE TITLE
panic after shift tab

### ISSUE THREAD

**Issue by ImLunaHey** [pvolok/mprocs#115]
<img width="1198" alt="Screenshot 2024-01-23 at 10 34 30 am" src="https://github.com/pvolok/mprocs/assets/105922175/8ea2ea4d-eafe-4f3c-b666-597b0376905e">

**Comment by IroncladDev** [comment]
Ran into the same issue

**Comment by IroncladDev** [comment]
As a temporary workaround, I set the `Shift-Tab` keybind in my terminal emulator (Alacritty) to do nothing.

```
[keyboard]
bindings = [
  { key = "Tab", mods = "Shift", chars = "" }
]
```

This disables the keybind from **crashing** mprocs but it does not resolve the issue.

**Comment by ankush** [comment]
This is fixed in development (unreleased) version - https://github.com/pvolok/mprocs/blob/a20a4726509592dcb59d0108a2249fa0a9555523/src/encode_term.rs#L554 

`BackTab` is handled in all cases from what I can tell.
