### ISSUE TITLE
Messy interface inside GNU Screen

### ISSUE THREAD

**Issue by scarduck** [pvolok/mprocs#13]
$ date
`Thu May 26 00:46:39 -03 2022`

$ cat /etc/redhat-release 
`CentOS Linux release 7.9.2009 (Core)`

$ uname -r
`5.14.0-70.13.1.el9_0.x86_64`

$ screen --version
`Screen version 4.01.00devel (GNU) 2-May-06`

$ ./mprocs --version
`mprocs 0.2.2`

$ echo $TERM
`screen`

 print (running: './mcprocs top' inside a GNU screen session):
https://i.imgur.com/HIoGsiR.png

1) Issue only happens inside a screen. Directly from a normal TTY on the same machine it works just fine.
2) Tested with latest GNU screen version (4.09.00 (GNU) 30-Jan-22) and the same issue happens.
3) Tested with literally all $TERM modes my system supports via a script, no luck: here's link to all the modes I've tested: https://www.klgrth.io/paste/w3a5p
4) Inside a tmux session it works just fine, but I really want to use GNU screen.

Any clue?
Thank you in advance.

**Comment by pvolok** [comment]
I was happening because mprocs used rgb colors, which screen doesn't support by default (it's possible to change in screen's config though). I changed mprocs to only use 256 colors. The fix is included in the 0.2.3 release.
