### ISSUE TITLE
0.7 Roadmap

### ISSUE THREAD

**Issue by pvolok** [pvolok/mprocs#131]
It's been a while since the last release. I since experimented with a couple of big changes without finishing them. And those unfinished changes are preventing me from making a new release. Here is will track things that need to be fixed before the 0.7 release.

- [x] Escape sequences parser was changed. Implement all sequences supported in the previous implementation.
- [x] Now mprocs has client-server architecture. That allows detaching from mprocs and keep it running in the background. it mostly works, but has some unfinished parts. Fix old cli api without exposing server-client features.
- [x] Update changelog.

**Comment by ddofborg** [comment]
Would you mind sharing is any other [features](https://github.com/pvolok/mprocs/issues?q=is%3Aissue+is%3Aopen+feature) are going to be implemented?

**Comment by pvolok** [comment]
@ddofborg Well, a couple of them might have been implemented. I'll do through them and update the changelog before the release.

The good news is that I finally sat to work on this today and will be able to clean it up very soon! I hid the client-side mode for now, so one of two TODOs for 0.7 will be done this weekend.

**Comment by jayvdb** [comment]
Thanks for the release @pvolok .  Our CI installed the new version last night and the job behaved as expected, spinning up a set of services while integration tests were preformed.

**Comment by pvolok** [comment]
@jayvdb Awesome. Thanks for the confirmation.
