### ISSUE TITLE
Support multiple preconfigured environments

### ISSUE THREAD

**Issue by BrodieRobertson** [pvolok/mprocs#15]
When running mprocs it will load the set of programs in your config file, what I'd love to see is being able to define multiple environments.

So I could do something such as
`mprocs x` - which would load one set of programs
`mprocs y` - which would load another set
Etc until you've created all you need

Obviously this can be done when launching mprocs by listing out mprocs with programs to launch but having this in the config would streamline the process. It can also be done by changing you current directory and just having mprocs configs floating around your file system but that seems like a bizarre way to handle it.

**Comment by pvolok** [comment]
You can already do it by supplying the *--config/-c* argument:
`mprocs` - will use `mprocs.yaml` by default
`mprocs -c mprocs-x.yaml` - will use `mprocs-x.yaml` from current directory
