### ISSUE TITLE
Brew install issue on Linux

### ISSUE THREAD

**Issue by farzadmf** [pvolok/mprocs#24]
Helllo,

`brew install pvolok/mprocs/mprocs` is working fine in MacOS, but on Linux, it seems that the downloaded binary is missing the `x` permission:
```
ls -l /home/linuxbrew/.linuxbrew/Cellar/mprocs/0.3.0/bin

.r--r--r-- 492k farzadmf 29 May 17:16  mprocs
```

And, if I manually make it executable, I think it's somehow the MacOS executable because I get this error:
```
zsh: exec format error: mprocs
```

I see that installing on Linux through `brew` is not mentioned in the `README`, but usually there isn't a difference between Mac and Linux when they support installation through `brew`

**Comment by pvolok** [comment]
Indeed I only added brew distribution for macos only. I didn't know if anyone would install mprocs via homebrew on linux. Tomorrow I will release a new version and will add linux version on homebrew.

**Comment by farzadmf** [comment]
Great, glad to hear, thank you!

**Comment by pvolok** [comment]
It seems that homebrew formulae are source based and that's probably why they are by default supported on linux. I will have to investigate more how rust apps are distributed on homebrew. I'd prefer to avoid the rust dependency.

**Comment by farzadmf** [comment]
> I'd prefer to avoid the rust dependency

Makes sense.

As an example, [this](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/bat.rb) seems to be `bat`'s formula; thought it could be useful

**Comment by pvolok** [comment]
@farzadmf Sorry it took so long. Mprocs is now in the core homebrew repo and is available on Linux as well.
```sh
brew untap pvolok/mprocs
brew update
brew install mprocs
```

**Comment by farzadmf** [comment]
Wow, AMAZING 🚀🚀🚀 

Thank you so much for following up with this, much appreciated (I think I was the only one requesting this 😛)
