### ISSUE TITLE
Substitute names for commands

### ISSUE THREAD

**Issue by arifd** [pvolok/mprocs#25]
`concurrently` has:
> -n, --names           List of custom names to be used in prefix template.
                        Example names: "main,browser,server"            [string]
                        
Allowing us to have compact names that represent our commands, very convenient when dealing with long or similar looking commands.

Can we get something like this into `mprocs`?

**Comment by pvolok** [comment]
I added the *--names* argument in mprocs 0.4.0. You can see the docs for it by running `mprocs --help`.
Example: `mprocs htop nvim --names top,neovim`
