### ISSUE TITLE
[Feature request] Keep original terminal colors

### ISSUE THREAD

**Issue by 1gni5** [pvolok/mprocs#29]
Would it be possible to keep the original terminal colors ? Depending of the combinations the miss-match of colors make working with mprocs impossible.

## Usable but not very pretty
![Usable but not very pretty](https://i.imgur.com/7NwoUHk.png)

## Not usable at all
![Not usable because of mix of dark and light themes](https://i.imgur.com/cG2apeA.png)

**Comment by pvolok** [comment]
Yeah, I didn't put much effort into colors. Will revise it.

**Comment by serhez** [comment]
I second this! I have a `onedark` colorscheme in my terminal, and it is unusable. I don't think being able to configure custom colors is necessary, just sane defaults picking up the colors from the terminal colorscheme.

Btw, fantastic product idea, thanks for the work! It's missing a few things and fixes but it looks super promising to add it to my workflow.

**Comment by pvolok** [comment]
I switched to only basic 8 colors, which are defined by your terminal theme. It is now in master and I will release is today/tomorrow. Later I plan to add support to override the colors in the config.

**Comment by pvolok** [comment]
I released mprocs 0.4.1 which uses basic 8 colors. All elements are visible on my light theme. Feel free to reopen if there are still issues with a light theme.
