### ISSUE TITLE
[Feature request] Option to add new command to the list

### ISSUE THREAD

**Issue by fenilgmehta** [pvolok/mprocs#30]
Thanks a lot for developing such a great utility 🙂

### Current Behaviour
- Consider a situation where I start `mprocs` using `mprocs cmd1 cmdnN`
- Now, after 5 minutes I realise that I wanted to do `mprocs cmd1 cmd2 cmdN`, then I will have to quit `mprocs` and start it again with the new list (i.e. `mproc cmd1 cmd2 cmdN`)

### Expected Behaviour
- It would be wonderful if we could add new commands to the list
- I think letter `a` and `i` could be used for this, and their behaviour could be just like that seen in `vim`

**Comment by pvolok** [comment]
This is already possible! You can press `a` for adding a process and `d` for removing stopped process.

**Comment by fenilgmehta** [comment]
Awesome 🎉
Actually I had just read the help message that is shown at the bottom of `mprocs` when it is running.
Sorry for the inconvenience caused, and thanks for the help.
