### ISSUE TITLE
[Feature request] Optionally show the "help" bar

### ISSUE THREAD

**Issue by serhez** [pvolok/mprocs#33]
Hey!

Sorry for requesting so many features, but I'm loving `mprocs` 😄 

I would like to not have the "Help" bar showing at the bottom, so maybe an option in the global config could be introduced to not show it by default. Additionally, a keymap (such as `?`) could be set up to toggle the bar, or even better, a popup showing your keymaps.

There are two key reasons why I think this change would be helpful:
1. When running `mprocs` on a split `tmux` pane, the screen real state `mprocs` gets is quite small, so having an additional bar for keymaps you know by heart is not good.
2. If you heavily change the default keymaps for custom ones through the global config, the "Help" bar will continue showing the default keymaps which no longer apply to your instance of `mprocs`. This could be material for another issue, but I don't think it's an important problem: if you have made the effort to modify the default keymaps you probably remember the custom ones you configured.

Thanks once again! 😄

**Comment by pvolok** [comment]
Hi. Thanks for all the suggestions! I already have the keymap window in TODOs, but didn't think about hiding the Help pane. It makes sense. Thinking of mprocs in a small tmux window, it probably can be useful to make process list window width configurable. I will add these things in the TODO list.

**Comment by pvolok** [comment]
Mprocs 0.6 now has a `hide_keymap_window` config key (global or local config).

```yaml
hide_keymap_window: true
```
