### ISSUE TITLE
Indicate when a non visible process has received events

### ISSUE THREAD

**Issue by arifd** [pvolok/mprocs#40]
Thanks for adding the scroll wheel to the interface! It definitely makes it much more usable for me.

Now it would be very nice to know when an process I'm not looking at, has printed something to the terminal.

Initially I thought it should jump to that process, but that is not always what you want, perhaps better if the process name became bold, if you have not clicked into it since something was printed into that terminal.

**Comment by pvolok** [comment]
I like the idea of making the process with activity bold. Added to the TODO list.

**Comment by pvolok** [comment]
This feature is now released in mprocs 0.6.
