### ISSUE TITLE
Add MPR installation instructions

### ISSUE THREAD

**Issue by hwittenborn** [pvolok/mprocs#42]
Hi! I've recently added mprocs to the [MPR](https://mpr.makedeb.org/packages/mprocs), which is an AUR-like platform for Debian and Ubuntu based systems. It's a platform I've created, but it's seen quite a bit of adoption and growth in popularity, and I think it could be beneficial to potential users of mprocs who are on Debian/Ubuntu systems.

Would there be any interest to get it listed in the README as an installation option?

**Comment by hwittenborn** [comment]
I've also added mprocs to the [Prebuilt-MPR](https://docs.makedeb.org/prebuilt-mpr/introduction/) if there's any interest for that - it's like the MPR, but it provides mprocs as a prebuilt package (the MPR serves source packages that are built by the end user).

**Comment by pvolok** [comment]
Nice project! Thanks for adding mprocs. Sure, I'd be happy to have MPR as an option in README.

**Comment by hwittenborn** [comment]
Thanks! Should I just create a PR for it?

**Comment by pvolok** [comment]
That would be nice.

**Comment by hwittenborn** [comment]
Alright, sounds great! I won't be home until Friday night but I'll try to get something going then.
