### ISSUE TITLE
Show a warning when quitting while processes are still running

### ISSUE THREAD

**Issue by hwittenborn** [pvolok/mprocs#45]
If I try to quit mprocs while processes are still running, mprocs shows no warning and just quits. I think it would be wise to show a warning though in case one of the running processes is doing something important.

**Comment by pvolok** [comment]
Indeed it's too easy to quit by accident. I will add this in the next version.

**Comment by pvolok** [comment]
Fixed since 0.6.1

**Comment by King-Aardvark** [comment]
Is it possible to disable the warning? In case I am doing something unimportant?  :smile: 

If it's not possible can I submit a pull request that adds a config option to disable it?
