### ISSUE TITLE
Resize Processes tab feature

### ISSUE THREAD

**Issue by diego-rapoport** [pvolok/mprocs#46]
I'd like to request a resizing of the Processes tab. Sometimes it takes much more of my terminal size than I'd like to.
Not proficient in Rust, but if you give me a guideline I could try to do that too.

**Comment by pvolok** [comment]
It's very easy to add. I'll add in in the next version. In fact, I already wanted to include it in the current version, but didn't have time.

**Comment by pvolok** [comment]
Now the process list width can be set in `mprocs.yaml`:
```yaml
procs_list_width: 20
```

**Comment by diego-rapoport** [comment]
Thank you very much!! I'm really happy using mprocs on my daily basis at work and home.
