### ISSUE TITLE
Ability to add and remove process

### ISSUE THREAD

**Issue by sahilsehwag** [pvolok/mprocs#5]
Hey, I have been using mprocs with my tmux workflows, and its been great. It fills out this big gap in my tmux workflow of running multiple project tasks. I would love to suggest some features based on my experience. mprocs just blends in with tmux workflows really smoothly

* Ability to add process to a running instance of mprocs
* Ability to remove process from a running instance of mprocs

Flow would look like:
* Adding/removing process either through TUI interface or programatically, kind of like `tmux sessions` where we can specify the target instance of `mprocs`, in case if there are multiple instances running on this machine/server
* for ex: `mprocs add "cmd" -t|--target <id, name or some identifier>`

To implement above feature:
* It would be easier if we can keep track of multiple instance of mprocs (like sessions)
* Ability to assign `name` to an instance, so its easier to specify target instance to which we want to add/remove cmd/process
* Ability to do all mprocs operations through shell command (like tmux) so that we can programatically perform actions like starting, stopping, toggling, adding, deleting some task
* Or opening/closing/renaming instance of mprocs with specified name
* This will help plugin authors to make integrations plugins for mprocs where we can programatically add or remove some project task to/from a mprocs instance(let's say running for the current project)
* and many more possibilities will be possible, since exposing all operations will give users more flexibility due to programatic access

**Comment by pvolok** [comment]
I really like your idea of controlling mprocs from outside. I couple of points:

- I'd like to keep mprocs as stateless as possible and avoid dealing with daemons and having different instances knowing about each other. But we can add a `server` option (configurable via config file and cli args) like this `mprocs --server <port or socket path>`, which would make mprocs listen for external commands.
- By default, mprocs treats positional arguments as commands to run: `mprocs <cmd1> <cmd2> ...`. An argument would be required to use mprocs as a client; something like this: `mprocs --ctl "add NAME CMD"`.

**Comment by pvolok** [comment]
Version 0.3.0 of mprocs supports adding/removing processes and has remote control feature. The api is not very powerful, but I think it will be possible to extend it without breaking api.
