### ISSUE TITLE
Mprocs Version

### ISSUE THREAD

**Issue by diego-rapoport** [pvolok/mprocs#52]
I don't really know why but installing mprocs from Arch's repository(I'm using yay to do it) it says the version is 0.6.2-1 and when I run `mprocs -V` it shows me `mprocs 0.5.0`.

**Comment by pvolok** [comment]
I think @1995parham is updating mprocs in AUR. Seems to be wrong version of mprocs, it's unlikely to be a problem in the code.

**Comment by 1995parham** [comment]
Thanks for reporting it. I will check this and report it here.

**Comment by 1995parham** [comment]
@diego-rapoport can you please send me the exact package you are using (`mprocs` or `mprocs-bin`)? I also install it with `mprocs` and its version is correct:

```

```

**Comment by diego-rapoport** [comment]
> @diego-rapoport can you please send me the exact package you are using (`mprocs` or `mprocs-bin`)? I also install it with `mprocs` and its version is correct:
> 
> ```
> mprocs -V
> > mprocs 0.6.2    
> ```

I was using mprocs

**Comment by 1995parham** [comment]
Can you please remove `$HOME/.cache/yay/mprocs` and then reinstall the package? Maybe you clone from AUR uses the version with issue that cause this.

**Comment by diego-rapoport** [comment]
I usually do clean all cache on updates. To solve it quickly I installed via cargo and it's all fine. Just reporting it!
