### ISSUE TITLE
Mprocs panic after exit zoom mode

### ISSUE THREAD

**Issue by namespaceYcZ** [pvolok/mprocs#56]
If the program [termusic](https://github.com/tramhao/termusic) is running in mprocs, then mprocs will panic after exit zoom mode. It seems that other programs will not make mprocs panic.
(Not sure if mprocs works well with other terminal music player or not. Termusic is the only terminal music player that can run in my Windows Ternimal.)

![p-1](https://user-images.githubusercontent.com/3965259/187062502-ff68369c-4bd3-45c3-bc1e-6f426a4d44d2.jpg)
![p2](https://user-images.githubusercontent.com/3965259/187062506-8f85c2fc-01cb-4473-b76d-823dee385cc9.jpg)
(zoom mode and exit zoom mode works ok while termusic is down)
![p3](https://user-images.githubusercontent.com/3965259/187062510-fbf0ac4b-2f29-489f-8982-dc20be3a2ede.jpg)
![p4](https://user-images.githubusercontent.com/3965259/187062511-a7a31d32-14dc-422d-b0f6-6ed4b624513f.jpg)
![p-5](https://user-images.githubusercontent.com/3965259/187062513-a2986928-c0ed-4234-9d30-450d888a64ad.jpg)
(panic after exit zoom mode, while termusic is up)
### Platform
Windows 11 21H2 22000.856
### Terminal Emulator
Windows Terminal 1.1422.82.0
### mprocs version
0.6.3
### termusic version
0.7.3

**Comment by pvolok** [comment]
I tried to zoom in/out termusic in mprocs on Windows and it worked well. From this error it is not clear what went wrong. But I see that error handling should be improved.

**Comment by namespaceYcZ** [comment]
It seems that this problem has been sovled by the new version 0.6.4.
