### ISSUE TITLE
Missing pre-built binaries

### ISSUE THREAD

**Issue by 1995parham** [pvolok/mprocs#63]
I want to update `mprocs-bin` on AUR, but the new release (v0.6.4) lacks the pre-built binaries.

**Comment by pvolok** [comment]
Thank you for updating mprocs in AUR. After adding lua, I can't cross compile mprocs. But I will compile it later today. Sorry for the delay.

**Comment by pvolok** [comment]
I will post it here, when the binaries are uploaded.

**Comment by pvolok** [comment]
@1995parham I finally uploaded linux amd64 binary. But I still can't compile arm version with musl lib.

**Comment by 1995parham** [comment]
Great, I will update the aur package
