### ISSUE TITLE
excess transformed path

### ISSUE THREAD

**Issue by hxse** [pvolok/mprocs#65]
```
  webdav-e:
    cmd: ['wsgidav','--host=0.0.0.0','--port=8001','--root="E:\test demo"','--auth=anonymous']
```
When i run it, i get
![image](https://user-images.githubusercontent.com/22582226/218251635-137e2ec5-c8c6-4da0-916d-d9160e5c0b2e.png)
Why does path `"E:\test demo"` transformed to path `C:\Users\hxse\"E:\test demo"`
I don't want the path to be transformed, How to keep the path like the original.

**Comment by pvolok** [comment]
I think the problem is how wsgidav interprets cli arguments. Try to pass the path without double quotes.
