### ISSUE TITLE
How to view the executed command

### ISSUE THREAD

**Issue by hxse** [pvolok/mprocs#66]
when i run:
```
  ping:
    cmd: ['ping', 'www.google.com']
```
In mprocs:
![image](https://user-images.githubusercontent.com/22582226/218251871-88e2e5d9-5661-4796-839b-dfc48060d3dc.png)

In powershell: 
![image](https://user-images.githubusercontent.com/22582226/218251940-57ae4f99-34d3-496d-af91-8c6972cb36d0.png)

How to show executed command `ping www.google.com`, I want to show it in the first line, just like common terminal

**Comment by pvolok** [comment]
The first line in powershell is part of the shell (powershell). But mprocs will just print process's output. You can create a script file that would print anything and run another process:

```cmd
print "Executing: ping google.com"
ping google.com
```

And then run this script though mprocs:
```yaml
procs:
  shell: your-script.cmd
```

**Comment by hxse** [comment]
`^^^&` can pass to .bat
