### ISSUE TITLE
Feature Request - Auto restart

### ISSUE THREAD

**Issue by jjanyan** [pvolok/mprocs#68]
Our team currently uses [DarthSim/overmind](https://github.com/DarthSim/overmind) to manage running processes during local development. 

Mprocs looks compelling, especially because it can split the output of all of the processes. One feature we'd need to switch is automatic restarts.

Thoughts? Thanks for considering!

**Comment by pvolok** [comment]
This is definitely a feature that I'd like to have in mprocs. I am planning to make a small release soon and will make sure to include this feature.

**Comment by agirorn** [comment]
A workaround I use for now is to simply wrap the shell command in a loop like so:

```yaml
procs:
  node-forever:
    shell: while true; do node index.js; done
```

This is working so far in zsh shell
