### ISSUE TITLE
remove-proc remote control command

### ISSUE THREAD

**Issue by SijanC147** [pvolok/mprocs#70]
Hi, maybe i'm missing something, but what is the "<PROCESS ID>"  that is required by the remove-proc rc-command? i tried the name of the process but the rc-command expects this to value to be of type `usize` not `string`, however using the `index` didn't work either, i'm wondering where can I find this `id` value? 

Thanks

**Comment by pvolok** [comment]
That is an internal process id in mprocs. Unfortunately currently there is no way to retrieve it from outside.

I am currently rethinking some parts of mprocs and preparing a refactoring. As part of it I want to give remote control api more attention.

**Comment by SijanC147** [comment]
ahh ok, understood. Thanks for the response, keep up the great work man 👏
