### ISSUE TITLE
Packaging for NixOs

### ISSUE THREAD

**Issue by GaetanLepage** [pvolok/mprocs#8]
Hello !

I would just like to inform you that I initiated a PR to get this as a NixOS package :)

https://github.com/NixOS/nixpkgs/pull/174096

**Comment by pvolok** [comment]
Nice! Let's keep this issue open until the package is available on nixpkgs and we added installation instructions into README.

**Comment by GaetanLepage** [comment]
It has been merge a few hours ago ! Closing this issue
