### ISSUE TITLE
Packaging for Arch by AUR

### ISSUE THREAD

**Issue by 1995parham** [pvolok/mprocs#9]
I have created the following package for Arch Linux with AUR.

- [mprocs-bin](https://aur.archlinux.org/packages/mprocs-bin)
- [mprocs](https://aur.archlinux.org/packages/mprocs)

**Comment by 1995parham** [comment]
Sure, I will add this into README.

**Comment by benlodz** [comment]
The PKGBUILD for the mprocs package on the AUR has a typo in it. It'll fail to build because it's missing the 'o' in mprocs. I corrected it and it worked for me.

**Comment by 1995parham** [comment]
@benlodz thanks for mentioning it. I fixed it.

**Comment by benlodz** [comment]
No problem, I actually forgot to mention something though. I also replaced the greet-d with "mprocs-". 
So the whole command for me looked like this: `install -Dm755 "$srcdir/mprocs-$pkgver/target/release/mprocs" \`
